/**
 * 种子产品目录：模块自带的一手数据源（参数/价格/评价聚合/媒体入口）。
 *
 * 定位：demo 与冷启动数据，字段结构与真实 ingest 产物一致——后续接真实
 * 商品库/评价抓取时只换数据不换 schema。价格渠道为编制时参考价（sources
 * 里会如实标注「商品库参考价」），不冒充实时价。
 */

import type { ProductRecord } from "./product-catalog.js";

export const SEED_PRODUCTS: ProductRecord[] = [
  {
    id: "p-sonny-xm5",
    brand: "Sony",
    name: "WH-1000XM5 头戴降噪耳机",
    category: "audio",
    tags: ["降噪", "耳机", "通勤", "头戴"],
    desc: "旗舰级主动降噪头戴耳机，8 麦克风降噪、30 小时续航、支持 LDAC，主打通勤与长途差旅场景。",
    image: "/api/recommendation/media/sony-xm5.jpg",
    specs: [
      { label: "降噪", value: "8 麦克风主动降噪，GN 自动风噪抑制" },
      { label: "续航", value: "约 30 小时（开降噪），快充 3 分钟用 3 小时" },
      { label: "重量", value: "约 250g" },
      { label: "编码", value: "SBC / AAC / LDAC" },
      { label: "通话", value: "4 麦克风 AI 通话降噪" },
    ],
    channels: [
      { name: "京东自营", priceCny: 2199, url: "https://search.jd.com/Search?keyword=WH-1000XM5" },
      { name: "天猫旗舰店", priceCny: 2249, url: "https://sony.tmall.com" },
      { name: "拼多多百亿补贴", priceCny: 1899, url: "https://mobile.yangkeduo.com" },
    ],
    reviewSummary: {
      pros: ["降噪第一梯队", "佩戴轻", "续航扎实"],
      cons: ["不可折叠仅平折", "音质偏流行调音", "耳罩偏小"],
      suitedFor: "通勤/差旅降噪刚需、iOS+安卓双端用户",
      avoidIf: "追求可折叠便携、重低音烧友、预算 1500 以内",
      sampleSize: 3200,
      updatedAt: 1758381600000,
    },
    media: [
      {
        type: "video",
        title: "B 站评测检索：WH-1000XM5 深度评测/佩戴/降噪实测",
        url: "https://search.bilibili.com/all?keyword=WH-1000XM5%20%E8%AF%84%E6%B5%8B",
        source: "bilibili",
      },
    ],
    seededAt: 1758381600000,
  },
  {
    id: "p-bose-qcu",
    brand: "Bose",
    name: "QuietComfort Ultra 头戴降噪耳机",
    category: "audio",
    tags: ["降噪", "耳机", "通勤", "头戴"],
    desc: "Bose 旗舰降噪耳机，CustomTune 智能调校、沉浸式空间音频、可折叠设计，降噪与佩戴舒适度口碑突出。",
    image: "/api/recommendation/media/bose-qcu.jpg",
    specs: [
      { label: "降噪", value: "CustomTune 智能耳内调校，动态音质降噪" },
      { label: "续航", value: "约 24 小时（开降噪），快充 15 分钟用 2.5 小时" },
      { label: "重量", value: "约 250g" },
      { label: "编码", value: "SBC / AAC / aptX Adaptive（Snapdragon Sound）" },
      { label: "折叠", value: "可折叠，附硬质收纳盒" },
    ],
    channels: [
      { name: "京东自营", priceCny: 2999, url: "https://search.jd.com/Search?keyword=Bose%20QC%20Ultra" },
      { name: "天猫旗舰店", priceCny: 3080, url: "https://bose.tmall.com" },
    ],
    reviewSummary: {
      pros: ["降噪第一梯队", "可折叠便携", "佩戴舒适度高"],
      cons: ["价格高于 XM5", "aptX Adaptive iPhone 用不上", "续航短于 XM5"],
      suitedFor: "常折叠携带、重舒适度与沉浸感的安卓用户",
      avoidIf: "预算 2500 内、超长续航刚需、iPhone 想要满血编解码",
      sampleSize: 2100,
      updatedAt: 1758381600000,
    },
    media: [
      {
        type: "video",
        title: "B 站评测检索：Bose QC Ultra 对比 XM5/佩戴实测",
        url: "https://search.bilibili.com/all?keyword=Bose%20QC%20Ultra%20%E5%AF%B9%E6%AF%94%20XM5",
        source: "bilibili",
      },
    ],
    seededAt: 1758381600000,
  },
  {
    id: "p-huawei-gt5",
    brand: "华为",
    name: "WATCH GT5 Pro 智能手表",
    category: "wearable",
    tags: ["智能手表", "运动", "续航", "健康"],
    desc: "长续航智能手表，21 天续航、ECG 心电、 free dive 潜水级防水，运动健康监测全面。",
    specs: [
      { label: "续航", value: "典型 14 天（Pro 钛金属款 21 天）" },
      { label: "健康", value: "ECG 心电 / 血氧 / 体脂 / 情绪" },
      { label: "防水", value: "5ATM + IP69K，支持自由潜" },
      { label: "运动", value: "100+ 模式，跑步/骑行/高尔夫" },
      { label: "系统", value: "HarmonyOS，安卓/iOS 均可配对（部分功能限华为手机）" },
    ],
    channels: [
      { name: "京东自营", priceCny: 2688, url: "https://search.jd.com/Search?keyword=WATCH%20GT5%20Pro" },
      { name: "Vmall 商城", priceCny: 2688, url: "https://www.vmall.com" },
    ],
    reviewSummary: {
      pros: ["续航远超智能表", "健康监测全", "钛金属质感好"],
      cons: ["第三方应用生态弱", "非华为手机部分功能阉割", "表体偏重"],
      suitedFor: "重续航与健康的运动人群、安卓用户",
      avoidIf: "重度 App 生态玩家、iPhone 深度用户想要完整功能",
      sampleSize: 1800,
      updatedAt: 1758381600000,
    },
    media: [
      {
        type: "video",
        title: "B 站评测检索：WATCH GT5 Pro 上手/对比实测",
        url: "https://search.bilibili.com/all?keyword=WATCH%20GT5%20Pro%20%E8%AF%84%E6%B5%8B",
        source: "bilibili",
      },
    ],
    seededAt: 1758381600000,
  },
  {
    id: "p-keychron-k5",
    brand: "Keychron",
    name: "K5 Pro 超薄机械键盘",
    category: "peripheral",
    tags: ["机械键盘", "办公", "无线", "超薄"],
    desc: "超薄矮轴机械键盘，98 配列、三模无线、热插拔，Mac/Win 双系统键帽，办公桌面友好。",
    image: "/api/recommendation/media/keychron-k5.jpg",
    specs: [
      { label: "配列", value: "98 配列（带方向键与数字区）" },
      { label: "轴体", value: "Gateron 矮轴，支持热插拔" },
      { label: "连接", value: "蓝牙 5.1 / 2.4G / Type-C 三模" },
      { label: "系统", value: "Mac / Win 双系统，键帽即换即用" },
      { label: "背光", value: "白光/RGB 可选" },
    ],
    channels: [
      { name: "京东自营", priceCny: 468, url: "https://search.jd.com/Search?keyword=Keychron%20K5%20Pro" },
      { name: "官网", priceCny: 449, url: "https://www.keychron.com" },
    ],
    reviewSummary: {
      pros: ["薄且不牺牲手感", "三模切换方便", "Mac 兼容好"],
      cons: ["矮轴手感与传统轴不同", "大键位有轻微空腔音", "无线模式延迟一般不适合竞技"],
      suitedFor: "Mac 双系统办公、想要轻薄桌面的人群",
      avoidIf: "电竞延迟敏感、只爱传统高度轴体手感",
      sampleSize: 900,
      updatedAt: 1758381600000,
    },
    media: [
      {
        type: "video",
        title: "B 站评测检索：Keychron K5 Pro 开箱/矮轴手感",
        url: "https://search.bilibili.com/all?keyword=Keychron%20K5%20Pro%20%E8%AF%84%E6%B5%8B",
        source: "bilibili",
      },
    ],
    seededAt: 1758381600000,
  },
  {
    id: "p-lg-4k-27",
    brand: "LG",
    name: "27UP850 27 英寸 4K 显示器",
    category: "display",
    tags: ["显示器", "4K", "Type-C", "办公"],
    desc: "27 英寸 4K IPS 显示器，95% DCI-P3、Type-C 90W 反充、HDR400，生产力与轻度修图兼顾。",
    specs: [
      { label: "面板", value: "27\" IPS 4K（3840×2160）60Hz" },
      { label: "色域", value: "95% DCI-P3，出厂校色" },
      { label: "接口", value: "Type-C 90W 反充 + 2×HDMI + DP" },
      { label: "HDR", value: "HDR400" },
      { label: "支架", value: "升降旋转，支持 VESA" },
    ],
    channels: [
      { name: "京东自营", priceCny: 2399, url: "https://search.jd.com/Search?keyword=LG%2027UP850" },
      { name: "天猫旗舰店", priceCny: 2459, url: "https://lg.tmall.com" },
    ],
    reviewSummary: {
      pros: ["4K 文字锐利", "Type-C 一线连笔记本", "色准够修图入门"],
      cons: ["60Hz 不适合高刷游戏", "HDR400 效果有限", "扬声器一般"],
      suitedFor: "Mac/笔记本办公外接、修图入门、代码多窗口",
      avoidIf: "高刷游戏玩家、HDR 电影党",
      sampleSize: 1500,
      updatedAt: 1758381600000,
    },
    media: [
      {
        type: "video",
        title: "B 站评测检索：27UP850 实测/修图色准",
        url: "https://search.bilibili.com/all?keyword=LG%2027UP850%20%E8%AF%84%E6%B5%8B",
        source: "bilibili",
      },
    ],
    seededAt: 1758381600000,
  },
  {
    id: "p-mi-luggage20",
    brand: "小米",
    name: "小米旅行箱 20 寸万向轮",
    category: "luggage",
    tags: ["行李箱", "登机", "旅行", "便携"],
    desc: "20 寸登机行李箱，德国拜耳 PC 材质、万向静音轮、TSA 密码锁，短途差旅与登机友好。",
    specs: [
      { label: "尺寸", value: "20 寸（可登机）368×250×560mm" },
      { label: "材质", value: "德国拜耳 PC，防刮纹理" },
      { label: "轮子", value: "万向静音轮" },
      { label: "锁具", value: "TSA 海关密码锁" },
      { label: "重量", value: "约 2.9kg" },
    ],
    channels: [
      { name: "京东自营", priceCny: 249, url: "https://search.jd.com/Search?keyword=%E5%B0%8F%E7%B1%B3%E6%97%85%E8%A1%8C%E7%AE%B1%2020%E5%AF%B8" },
      { name: "小米商城", priceCny: 249, url: "https://www.mi.com" },
    ],
    reviewSummary: {
      pros: ["两百价位质感超预期", "轮子顺滑安静", "自重轻"],
      cons: ["拉链非金属防爆款", "深色款易留划痕", "扩展层较小"],
      suitedFor: "高频短途差旅、预算 300 内的登机箱",
      avoidIf: "需要托运大容量、暴力托运环境多",
      sampleSize: 5200,
      updatedAt: 1758381600000,
    },
    media: [
      {
        type: "video",
        title: "B 站评测检索：小米旅行箱 20 寸 耐造/对比",
        url: "https://search.bilibili.com/all?keyword=%E5%B0%8F%E7%B1%B3%E6%97%85%E8%A1%8C%E7%AE%B1%2020%E5%AF%B8%20%E8%AF%84%E6%B5%8B",
        source: "bilibili",
      },
    ],
    seededAt: 1758381600000,
  },
  {
    id: "p-nespresso-essenza",
    brand: "Nespresso",
    name: "Essenza Mini 胶囊咖啡机",
    category: "appliance",
    tags: ["咖啡", "胶囊机", "家用", "小巧"],
    desc: "紧凑型胶囊咖啡机，一按出杯、19 bar 泵压、机身小巧，适合办公室与单人早餐场景。",
    specs: [
      { label: "泵压", value: "19 bar" },
      { label: "杯量", value: "Espresso / Lungo 两档" },
      { label: "体积", value: "宽 8cm 级机身，约 2.4kg" },
      { label: "预热", value: "约 25 秒" },
      { label: "耗材", value: "Nespresso 原装/兼容胶囊（约 2-4 元/颗）" },
    ],
    channels: [
      { name: "京东自营", priceCny: 649, url: "https://search.jd.com/Search?keyword=Nespresso%20Essenza%20Mini" },
      { name: "天猫旗舰店", priceCny: 699, url: "https://nespresso.tmall.com" },
    ],
    reviewSummary: {
      pros: ["零操作门槛", "占地极小", "出杯稳定"],
      cons: ["胶囊长期成本高于现磨", "只出黑咖不带奶泡", "水泵声音明显"],
      suitedFor: "办公室/单人日常、要省事稳定的一杯",
      avoidIf: "想要奶咖一体、在意单杯成本、追求现磨风味",
      sampleSize: 2600,
      updatedAt: 1758381600000,
    },
    media: [
      {
        type: "video",
        title: "B 站评测检索：Essenza Mini 使用/胶囊成本核算",
        url: "https://search.bilibili.com/all?keyword=Essenza%20Mini%20%E8%AF%84%E6%B5%8B",
        source: "bilibili",
      },
    ],
    seededAt: 1758381600000,
  },
  {
    id: "p-lip-chili",
    brand: "MAC",
    name: "Chili 小辣椒口红（砖红棕）",
    category: "cosmetics",
    tags: ["口红", "试色", "显白", "化妆品"],
    desc: "经典砖红棕色哑光口红，黄皮友好的显白气场色，上色效果浓郁，通勤到晚宴都压得住。",
    image: "/api/recommendation/media/lip-redbrick.jpg",
    specs: [
      { label: "色号", value: "Chili（砖红棕）" },
      { label: "质地", value: "Matte 哑光" },
      { label: "显白", value: "暖皮黄皮友好，气场强" },
      { label: "持久", value: "约 6 小时，轻微沾杯" },
      { label: "滋润", value: "偏干，建议先打底" },
    ],
    channels: [
      { name: "京东自营", priceCny: 230, url: "https://search.jd.com/Search?keyword=MAC%20Chili" },
      { name: "天猫旗舰店", priceCny: 235, url: "https://mac.tmall.com" },
    ],
    reviewSummary: {
      pros: ["显白不挑皮", "气场强"],
      cons: ["偏干唇纹明显", "轻微沾杯"],
      suitedFor: "暖黄皮、日常通勤到晚宴",
      avoidIf: "唇部状态差怕干、喜欢水光感",
      sampleSize: 4600,
      updatedAt: 1758381600000,
    },
    media: [
      {
        type: "video",
        title: "B 站试色检索：MAC Chili 上唇实测/黄皮试色",
        url: "https://search.bilibili.com/all?keyword=MAC%20Chili%20%E8%AF%95%E8%89%B2",
        source: "bilibili",
      },
    ],
    seededAt: 1758381600000,
  },
  {
    id: "p-lip-dior720",
    brand: "Dior",
    name: "烈艳蓝金 720 口红（豆沙玫瑰）",
    category: "cosmetics",
    tags: ["口红", "试色", "显白", "化妆品"],
    desc: "豆沙玫瑰色丝绒口红，冷暖皮通用的温柔百搭色，上色效果自然提升气色，约会与正式场合皆宜。",
    image: "/api/recommendation/media/lip-rosewood.png",
    specs: [
      { label: "色号", value: "720（豆沙玫瑰）" },
      { label: "质地", value: "丝绒哑光" },
      { label: "显白", value: "冷暖皮通用，自然提气色" },
      { label: "持久", value: "约 5 小时" },
      { label: "滋润", value: "奶油感，相对滋润" },
    ],
    channels: [
      { name: "京东自营", priceCny: 395, url: "https://search.jd.com/Search?keyword=Dior%20720%20%E5%8F%A3%E7%BA%A2" },
      { name: "天猫旗舰店", priceCny: 430, url: "https://dior.tmall.com" },
    ],
    reviewSummary: {
      pros: ["温柔百搭", "质地舒服不拔干"],
      cons: ["价格偏高", "持色一般"],
      suitedFor: "冷白皮、约会与正式场合",
      avoidIf: "预算 300 内、重持久度",
      sampleSize: 3200,
      updatedAt: 1758381600000,
    },
    media: [
      {
        type: "video",
        title: "B 站试色检索：Dior 720 上唇试色/对比",
        url: "https://search.bilibili.com/all?keyword=Dior%20720%20%E8%AF%95%E8%89%B2",
        source: "bilibili",
      },
    ],
    seededAt: 1758381600000,
  },
];
